name: Run pre-commit hooks

on:
  workflow_call:

env:
  GO_VERSION: "1.16.6"

jobs:
   lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
          cache: true
      - name: Pre-commit checks
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
